alias vi="nvim"
alias ,s="source ~/.zshrc"
alias ,a="vi $ZDOTDIR/.alias.zsh"
alias ra='ranger'
alias vman='func(){vim -c "Man $1" -c "silent only"};func'
alias c="clear"
alias ll="ls -al"
alias cn="cd $MYNVIM"
alias ,e="vi ~/.config/nvim/init.vim"
alias ,z="vi $ZDOTDIR/zinit.zsh"
alias ,n="neofetch"
alias lg="lazygit"
alias his="history | fzf"
